Style/Documentation:
  Enabled: false

Style/AlignParameters:
  Description: 'Ruby code looks better with some flexibility on aligning params'
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false
