inherit_from:
  - .disabled-cops.yml

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
  Exclude:
    - db/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/routes.rb
    - db/**/*

Metrics/AbcSize:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  # Include common Ruby source files.
  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/*.opal'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/Berksfile'
    - '**/Cheffile'
    - '**/Vagabondfile'
    - '**/Fastfile'
    - '**/*Fastfile'
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'
